version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5111:5111
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - mxclfld
networks:
  mxclfld:
    name: mxclfld
